<div style="color: #8b1538; font-size: 38px">Julia 1.0 Programming</div>

<div class="alert alert-block alert-success">
    Run cells with python in Julia kernel
</div>

In [147]:
macro python_str(s) open(`python`,"w",stdout) do io; print(io, s); end; end  # pour écrire en python ds julia

@python_str (macro with 1 method)

### Println 

In [24]:
println("Welcome to Julia \nSuperbe")

Welcome to Julia 
Superbe


> Printstyled

In [23]:
printstyled("I love Julia!", color=:red, bold=true)

I love Julia!

> Commentaires

In [ ]:
# commentaire sur une ligne

In [ ]:
#= commentaires sur
plusieurs lignes
=#

> Reverse Uppercase

In [66]:
println(reverse("Hello")) # à l'envers
println(uppercase("Hello")) # en majuscule

olleH
HELLO


### Opérateur

In [9]:
println(1+3)
println(3^3)
println(20/3)
println(11%3)

4
27
6.666666666666667
2


> @Printf

In [88]:
using Printf

@printf("%d", 7.3) # d: entier
println()
@printf("%f\n", pi) # f: float
@printf("%0.2f", pi)  # float arrondi à .2

7
3.141593
3.14

In [100]:
python"""
import math
print("{:d}".format(7))  # 7.3 ne peut pas être mis
print("{:.0f}".format(7.3))
print("{}".format(math.pi))
print("{:.2f}".format(math.pi))  # round
"""

7
7
3.141592653589793
3.14


> Typeof Sizeof

In [10]:
x, x2, x3 = 7, Int8(7), 0.5
s = "Julia"

println("Type de x: $(typeof(x))")  # Type of the variable
println("Type de x2: $(typeof(x2))")
println("Type de x3: $(typeof(x3))")
println("Type de s: $(typeof(s))")

println("Taille de x : $(sizeof(x))") # Size of the variable
println("Taille de x2 : $(sizeof(x2))")
println("Taille de x3 : $(sizeof(x3))")
println("Taille de s : $(sizeof(s))")

Type de x: Int64
Type de x2: Int8
Type de x3: Float64
Type de s: String
Taille de x : 8
Taille de x2 : 1
Taille de x3 : 8
Taille de s : 5


In [37]:
z="1"  # qd "" -> string
z2='1' # qd '' -> character

print("z = $z is a $(typeof(z)), z2 = $z2 is a $(typeof(z2)) & ")
printstyled("z == z2 $(z == z2)", color=:red, bold=:true)

z = 1 is a String, z2 = 1 is a Char & z == z2 false

In [12]:
println("exemple impression de x: $x") # avec le "$"
println("ex impression de x: ",x) # avec la virgule en dehors des guillemets

exemple impression de x: 7
ex impression de x: 7


> Readline

In [15]:
name = readline() # fonction is used for takes value from user. 

stdin> Audrey


"Audrey"

In [16]:
println("Mon nom est $name.")

Mon nom est Audrey.


In [20]:
number=readline()  # a variable 'number' est un string 5.

stdin> 5


"5"

> Parse

In [21]:
println(number^3) # comme il s'agit d'un string, ça écrit 3 fois le 5. Il faut donc convertir la variable en entier. 
number=parse(Int,number) # 'parse' permet de convertir la variable.
println(typeof(number))
println(number^3)

555
Int64
125


In [29]:
x = 10^19 # Dépasse typemax(Int64) - result in wraparound behavior
x2 = big(10)^19

println("x: $(x) & type: $(typeof(x))\nx2: $(x2) & type: $(typeof(x2))")

x: -8446744073709551616 & type: Int64
x2: 10000000000000000000 & type: BigInt


### Help

In [101]:
? parse # comme un help

search: parse tryparse partialsortperm partialsortperm! pairs skipchars



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```


### Tranchage

In [38]:
j="Julia"
j[begin:end]

"Julia"

In [32]:
j[1]  # j[0] n'existe pas
j[begin]  # j[1] = j[begin]

'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

<div class="alert alert-block alert-warning">
    The index starts from 1 in julia
</div>

In [27]:
j[end] # last value

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [29]:
j[2:4] # return un string  de 2 à 4 inclus

"uli"

In [30]:
println(j[2:4])

uli


In [35]:
python"""
s = "Julia!"
s_start, s_end = s[:3], s[3:]

print("Start {} & End {}".format(s_start, s_end))
"""

Start Jul & End ia!


In [103]:
j="Julia is a programming language"

"Julia is a programming language"

> Substring

In [46]:
SubString(j,1,10)

"Julia is a"

In [47]:
SubString(j,11,31)
SubString(j,11) # de l'indice 11 jusqu'à la fin

" programming language"

### Concaténation

In [104]:
println(j, " pas de string.") # la variable j n'est pas changé car pas mis dans une variable.

j=string(j, " and is great.") # la varaible j est changé
println(j)

Julia is a programming language pas de string
Julia is a programming language and is great


In [105]:
length(j) # longueur

44

In [64]:
s = "hello" * " world"   # '*' for concatenation
s2 = string("hello", " world")
s3 = string(s, " with Julia")

print("s: $s \ns2: $s2 \ns3: $s3")

s: hello world 
s2: hello world 
s3: hello world with Julia

In [65]:
python"""
s = "abc" + "def"
print("s: {}".format(s))
"""

s: abcdef


> Findfirst

In [51]:
findfirst("programming", j) # pour savoir les indices du mot dans j. 

12:22

In [52]:
findfirst("Programming", j) # il ne renvoit rien car il n'existe pas

In [79]:
s = "hello world"

index = findfirst("hello", s)
index2 = findfirst("Julia", s)  # Renvoie nothing car n'existe pas

print("Indice de hello $index dans $s \nIndice de Julia $index2 dans $s")

Indice de hello 1:5 dans hello world 
Indice de Julia nothing dans hello world

> Occursin

In [53]:
println(occursin("language", j)) # si on trouve le mot ds j. 
println(occursin("Language", j))

true
false


> Replace

In [60]:
j="Julia"
j = replace(j, "u" => "o")
println("j_replace: $j")

j_replace: Jolia


In [61]:
python"""
j = "Julia"
j = j.replace("u", "o")
print("j_replace: {}".format(j))
"""

j_replace: Jolia


> Split

In [70]:
s = "hello world"
s = split(s, " ")  # return an array of String
print("s_split: $s")

s_split: SubString{String}["hello", "world"]

In [73]:
python"""
s = "hello world"
s = s.split(" ")
print("s_split: {}".format(s))
"""

s_split: ['hello', 'world']


### Range

In [106]:
for i in 1:5  # de 1 à 5 (inclus) par pas de 1 (par défaut)
    print("$i ")
end
println()

for i in 1:2:5  # de 1 à 5 (inclus) par pas de 2
    print("$i ")
end

1 2 3 4 5 
1 3 5 

In [107]:
python"""
for i in range(1, 6):  # de 1 à 6 (exclus) par pas de 1 - défaut
    print("{} ".format(i), end="")
print()

for i in range(1, 6, 2):  # de 1 à 6 (exclus) par pas de 2
    print("{} ".format(i), end="")
"""

1 2 3 4 5 
1 3 5 

-- ***Set up a macro range to have a python like syntax*** --

In [108]:
macro range(debut, fin, args...)
    if isempty(args)
        return debut:fin-1
    end
    return debut:args[1]:fin-1
end

@range (macro with 1 method)

> @range

In [109]:
for i in @range(1, 6)  # de 1 à 6 (exclus) par pas de 1 - défaut
    print("$i ")
end
println()

for i in @range(1, 6, 2)  # de 1 à 6 (exclus) par pas de 2
    print("$i ")
end

1 2 3 4 5 
1 3 5 

### Data-structure (Array) -> [ ]

-- ***Array is mutable*** --

In [110]:
num=[1,2,3] # Array d'entier {Int64}
show(num)

[1, 2, 3]

In [115]:
mix=[1,"2",3.0,4] # Array de différents types {Any} 
show(mix)
# typeof(mix)

Any[1, "2", 3.0, 4]

> Getindex

In [57]:
num=[1,2,3]
getindex(num,2)

2

> Eltype, Ndims, Length

In [178]:
num_type, num_dim, num_len = eltype(num), ndims(num), length(num)

print("Type $num_type \nTaille $num_len \nDimension $num_dim")

Type Int64 
Taille 3 
Dimension 1

> Indiçage

In [129]:
println("mix[3]: ", mix[3])
println("mix[2:3]: ", mix[2:3])
println("mix[1:4] = mix[begin:end]: ", mix[begin:end])

mix[3]: 3.0
mix[2:3]: Any["2", 3.0]
mix[1:4] = mix[begin:end]: Any[1, "2", 3.0, 4]


In [145]:
mix[4]=4.0 # On peut changer
show(mix)

Any[1, "2", 3.0, 4.0]

In [174]:
debut, fin = arr[begin], arr[end]  
print("Le 1er élément vaut $debut & le dernier élément vaut $fin.")

Le 1er élément vaut 1 & le dernier élément vaut 7.

In [176]:
python"""
l = list(range(1,8))
debut, fin = l[0], l[-1]
print("Le 1er élément vaut {} & le dernier élément vaut {}.".format(debut, fin))
"""

Le 1er élément vaut 1 & le dernier élément vaut 7.


> Collect

-- ***Initialize an array from a range*** --

In [168]:
range=collect(1:8)
show(range)

[1, 2, 3, 4, 5, 6, 7, 8]

In [169]:
python"""
l = list(range(1,9))
print(l)
"""

[1, 2, 3, 4, 5, 6, 7, 8]


In [171]:
macro collect(debut, fin, args...)
    if isempty(args)
        return collect(debut:fin-1)
    end
    return collect(debut:args[1]:fin-1)
end

@collect (macro with 1 method)

In [185]:
arr, arr2 = @collect(1,9), @collect(1, 9, 2)

([1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5, 7])

> Join

In [186]:
arr_join=join(arr," ") # il s'agit d'un string.
show(arr_join)
# typeof(arr_join)

"1 2 3 4 5 6 7 8"

In [189]:
#=
Pour python, il faut au préalable convertir chaque élément en string.
Car python ne permet pas de 'join' une liste en entier.
=#

python"""
l = list(range(1,9))
l = " ".join(str(ele) for ele in l) # string
print("{}".format(l))
# print(type(l))
"""

1 2 3 4 5 6 7 8


> Undef

-- ***array of random...*** --

In [141]:
arr = Array{Int8}(undef, 3)  # random int8
show(arr)

Int8[-112, -29, -88]

In [142]:
arr = Array{Int64}(undef, 3)  # random int64
show(arr)

[4575822624, 4713478016, 4713478032]

In [143]:
arr = Array{Float64}(undef, 3)  # random float64
show(arr)

[2.2608558577e-314, 2.3285427484e-314, 2.2945298227e-314]

> Push !

-- ***ajoute aux array (comme append)*** --

In [161]:
array=Int64[]
push!(array, 5, 66) # pour ajouter à la fin de l'array
show(array)

[5, 66]

In [162]:
python"""
l = []
l.append(5)
l.append(66)
print(l)
"""

[5, 66]


> Pop !

-- ***remove le dernier élément*** --

In [163]:
pop!(array) # pour supprimer la derniere valeur ajoutée
show(array)

[5]

In [166]:
python"""
l = []
l.append(5)
l.append(66)
print(l[:-1])
"""

[5]


> Append !

-- ***Concaténation*** --

In [202]:
a, b = [1, 7], [100, 200, 300]
append!(a, b)
show(a) # il y a tout dans a, mais b reste comme tel.

[1, 7, 100, 200, 300]

> Splice !

-- ***Remove un élément d'indice i*** --

In [203]:
supp = splice!(a, 3) # indice 3
println(supp) # l'indice 3 -> 100 est supprimé
show(a) 

100
[1, 7, 200, 300]

> in

-- ***For know if it's present or not*** --

In [211]:
in(200, a), in(100, a)
# Renvoie 'true' ou 'false'

(false, false)

> Sort !

-- ***Ranger par ordre croissant ou décroissant*** --

In [210]:
a = [16, 7, 2, 23, 2, 1]

sort!(a) # a.sort() en python
println("Sort par ordre croissant: $a")

sort!(a, rev=true)
println("Sort par ordre décroissant: $a")

Sort par ordre croissant: [1, 2, 2, 7, 16, 23]
Sort par ordre décroissant: [23, 16, 7, 2, 2, 1]


> Deepcopy

-- ***Renvoie une copy récursive ≠ copy pour une copy superficielle*** --

In [216]:
a = [1,2,4,6]
b = deepcopy(a)
b[end]=0

println("a = $a & b = $b")

a = [1, 2, 4, 6] & b = [1, 2, 4, 0]


### Matrice [ ]

In [61]:
m = [[1 2];[3 4]]
m = [1 2; 3 4] # On préviligera cette écriture

2×2 Array{Int64,2}:
 1  2
 3  4

In [65]:
m = rand(2,4) # matrice de taille 2lignes 5colonnes constitué de nb aléatoires entre 0 et 1.

2×4 Array{Float64,2}:
 0.556772  0.0070461  0.500052  0.353343
 0.972235  0.915571   0.400534  0.214419

> ndims, rows & cols

In [75]:
dim = ndims(m)
nrows = size(m,1)
ncols = size(m,2)
# nrows, ncols = size(m)

print("m est une matrice à $dim dimensions avec $nrows lignes & $ncols colonnes")

m est une matrice à 2 dimensions avec 2 lignes & 4 colonnes

> Trançage

In [77]:
# Sélectionner tout de la deuxième colonne.

m[:, 2]  # m[begin:end, n° de la colonne]

2-element Array{Float64,1}:
 0.0070460970453476435
 0.9155708041521768

In [82]:
# Sélectionner tout de la deuxième ligne.

m[2, :] # m[n° de la ligne, begin:end]

4-element Array{Float64,1}:
 0.9722347467958035
 0.9155708041521768
 0.40053427984196155
 0.2144187000658513

In [87]:
# Affecter 0 à tous les éléments de la deuxième ligne. 

m[2, :] .= 0  # m[2, :] = [0 0 0 0]
m

2×4 Array{Float64,2}:
 0.556772  0.0070461  0.500052  0.353343
 0.0       0.0        0.0       0.0

> Matrice transpose m'

In [90]:
m = [1 2; 3 4]
m'

2×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  3
 2  4

> Concaténation

In [98]:
#a = [1 2; 3 4]
#b = [5 6; 7 8]

a, b = [1 2; 3 4], [5 6; 7 8]

([1 2; 3 4], [5 6; 7 8])

In [99]:
# concaténation horizontale

h = hcat(a,b) 
# h = [a b]

2×4 Array{Int64,2}:
 1  2  5  6
 3  4  7  8

In [102]:
# concaténation verticale

v = vcat(a,b) 
# v = [a; b]

4×2 Array{Int64,2}:
 1  2
 3  4
 5  6
 7  8

### Data-structure (Tuple) -> ( )

- Tuple is immutable

In [104]:
nombre=(1,2,3) # que des Int
food=("pizza","burger","salade") # que des String
mix_tuple=(1,"2",3.0) # différents types 

println(typeof(nombre))
println(typeof(food))
println(typeof(mix_tuple))

Tuple{Int64,Int64,Int64}
Tuple{String,String,String}
Tuple{Int64,String,Float64}


In [108]:
t=(nourriture="tarte", item=["flour", "salt", "pepper"], salade="comcombre")

println(t)
println(t.item)

(nourriture = "tarte", item = ["flour", "salt", "pepper"], salade = "comcombre")
["flour", "salt", "pepper"]


> Trançage

In [50]:
println(food[1]) # food[0] n'existe pas
println(food[1:2])
println(food[begin:end])

pizza
("pizza", "burger")
("pizza", "burger", "salade")


> Reverse

In [67]:
println(reverse(mix_tuple)) # returner le tuple

(3.0, "2", 1)


> Tuple( )

In [109]:
seq = Tuple("AGTCTGGAC")

('A', 'G', 'T', 'C', 'T', 'G', 'G', 'A', 'C')

In [110]:
for nucleotide in seq
    print("$nucleotide ")
end

A G T C T G G A C 

### Data-structure (Dictionnary) -> { }

In [70]:
# structure KEY VALUE
#=
India > Delhi
USA > NY
France > Paris
=#

In [128]:
capital=Dict() # dico vide
capital["India"]="Delhi"
capital["Usa"]="NY"
capital["France"]="Paris"

println(capital)
println("La capital de l'Inde est: ", capital["India"])

Dict{Any,Any}("India" => "Delhi","Usa" => "NY","France" => "Paris")
La capital de l'Inde est: Delhi


In [129]:
# 2e façon d'écrir un dictionnaire. 
capital2 = Dict("France" => "Paris", "Russia" => "Moscow", "South Africa" => 
    ["Cape Town", "Pretoria"])

Dict{String,Any} with 3 entries:
  "South Africa" => ["Cape Town", "Pretoria"]
  "France"       => "Paris"
  "Russia"       => "Moscow"

In [149]:
pays = ["France", "Russia", "South Africa"]
capitals = ["Paris", "Moscow", Dict("Administrative" => "Pretoria", "Législative" => "Cape Town")]

capital3 = Dict(zip(pays, capitals))

Dict{String,Any} with 3 entries:
  "South Africa" => Dict("Administrative"=>"Pretoria","Législative"=>"Cape Town…
  "France"       => "Paris"
  "Russia"       => "Moscow"

In [130]:
capital["Usa"]="New York" # pr changer the value

"New York"

In [131]:
pop!(capital) # pr supprimer la premiere key-value ajoutée

println(capital) # India a disparu
capital[1] # correspondait à India

Dict{Any,Any}("Usa" => "New York","France" => "Paris")


LoadError: KeyError: key 1 not found

In [133]:
nb=Dict("a"=>1,"b"=>2,"c"=>3,"d"=>4,"e"=>5,"f"=>6)

Dict{String,Int64} with 6 entries:
  "f" => 6
  "c" => 3
  "e" => 5
  "b" => 2
  "a" => 1
  "d" => 4

In [141]:
println("La value de la clef b est: ", nb["b"]) # pr chercher s'il existe
println(nb["hfdg"]) # n'existe pas

La value de la clef b est: 2


LoadError: KeyError: key "hfdg" not found

> Get

In [142]:
get(nb,"a","null"), get(nb,"A","null")

#= Ds le dico 'nb' s'il y a la clef 'a', me retourner la value. 
Sinon me retourner 'null'.

Ds le dico 'nb' s'il y a la clef 'A', me retourner la value. 
Sinon me retourner 'null'.
=#

(1, "null")

> Haskey

In [143]:
haskey(nb, "c"), haskey(nb, "j")
# si la clef 'c' et 'j' sont présentes ou non. 

(true, false)

> Delete !

In [88]:
delete!(nb,"e") # pr supprimer la clef "e".

Dict{String,Int64} with 5 entries:
  "f" => 6
  "c" => 3
  "b" => 2
  "a" => 1
  "d" => 4

In [89]:
println(keys(nb))
println(values(nb))

["f", "c", "b", "a", "d"]
[6, 3, 2, 1, 4]


In [144]:
for pays in keys(capital2)
    print("$pays  ")
end

South Africa  France  Russia  

In [145]:
for capital in values(capital2)
    print("$capital  ")
end

["Cape Town", "Pretoria"]  Paris  Moscow  

In [146]:
for (pays, capital) in capital2
    println("$pays: $capital")
end

South Africa: ["Cape Town", "Pretoria"]
France: Paris
Russia: Moscow


In [148]:
python"""
dico = {'France': "Paris", 'Russia': "Moscow", 'South Africa': ["Cape Town", "Pretoria"]}

pays = ["France", "Russia", "South Africa"]
capital = ["Paris", "Moscow", {"Administrative": "Pretoria", "Législative": "Cape Town"}]
dico2 = dict(zip(pays, capital))

print("{}\n{}".format(dico, dico2), end="\n\n")

print("KEYS")
for pays in dico2.keys():
    print("{}  ".format(pays), end="")

print("\n\nVALUES")
for capital in dico2.values():
    print("{}  ".format(capital), end="")

print("\n\nITEMS")
for pays, capital in dico2.items():
    print("{}: {}".format(pays, capital))
"""

{'France': 'Paris', 'Russia': 'Moscow', 'South Africa': ['Cape Town', 'Pretoria']}
{'France': 'Paris', 'Russia': 'Moscow', 'South Africa': {'Administrative': 'Pretoria', 'Législative': 'Cape Town'}}

KEYS
France  Russia  South Africa  

VALUES
Paris  Moscow  {'Administrative': 'Pretoria', 'Législative': 'Cape Town'}  

ITEMS
France: Paris
Russia: Moscow
South Africa: {'Administrative': 'Pretoria', 'Législative': 'Cape Town'}


> Set

In [150]:
s, s2 = Set([1, 1, 25]), Set([7, 25])
push!(s, 1); push!(s, 13)

s, s2

(Set([25, 13, 1]), Set([7, 25]))

> Union, Intersect, Setdiff

In [151]:
println("Union: $(union(s, s2))")
println("Intersect: $(intersect(s, s2))")
println("Diff (s s2): $(setdiff(s, s2)) & Diff (s2 s): $(setdiff(s2, s))")

Union: Set([7, 25, 13, 1])
Intersect: Set([25])
Diff (s s2): Set([13, 1]) & Diff (s2 s): Set([7])


### Boucles If and While

In [90]:
n=0

while n<5 # pas de ':'
    n +=1
    println(n)
end # on fini la boucle avec un 'end'

1
2
3
4
5


In [91]:
for n in 1:5
    println(n)
end

1
2
3
4
5


In [92]:
for n in 1:5
    println(n, ":", n*n)
end

1:1
2:4
3:9
4:16
5:25


In [93]:
arr=[1,4,9,12,16,25]

i=1 # si i=0, ne fonctionne pas car commence à 1.
while i<=length(arr)
    println(arr[i])
    i+=1
end

1
4
9
12
16
25


In [94]:
for n in arr
    println(n)
end

1
4
9
12
16
25


In [95]:
m,n=5,3 # m=5 lignes  n=3 colonnes
A=rand(1:10,(m,n)) # random fonction

5×3 Array{Int64,2}:
 4  10  9
 6   3  1
 7   8  2
 3   2  9
 7   6  4

In [96]:
B=fill(0,(m,n)) # methode fill -> remplir un array d'un chiffre.

5×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0

In [97]:
?rand

search: rand randn transcode macroexpand @macroexpand @macroexpand1



```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:9` or `('x', "y", :z)`),
  * an `AbstractDict` or `AbstractSet` object,
  * a string (considered as a collection of characters), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), to $[0, 1)$ for floating point numbers and to $[0, 1)+i[0, 1)$ for complex floating point numbers;

`S` defaults to [`Float64`](@ref). When only one argument is passed besides the optional `rng` and is a `Tuple`, it is interpreted as a collection of values (`S`) and not as `dims`.

!!! compat "Julia 1.1"
    Support for `S` as a tuple requires at least Julia 1.1.


# Examples

```julia-repl
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> using Random

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2

julia> rand((2, 3))
3

julia> rand(Float64, (2, 3))
2×3 Array{Float64,2}:
 0.999717  0.0143835  0.540787
 0.696556  0.783855   0.938235
```

!!! note
    The complexity of `rand(rng, s::Union{AbstractDict,AbstractSet})` is linear in the length of `s`, unless an optimized method with constant complexity is available, which is the case for `Dict`, `Set` and `BitSet`. For more than a few calls, use `rand(rng, collect(s))` instead, or either `rand(rng, Dict(s))` or `rand(rng, Set(s))` as appropriate.



In [98]:
rand(Int,5) # va générer 5 chiffres entiers aléatoirement

5-element Array{Int64,1}:
  7817736312498672269
 -6801492675777894149
  1648002693673193281
   323740819838151269
 -5011619789876617563

In [99]:
rand(Float64,5) # va générer 5 chiffres décimales aléatoirement

5-element Array{Float64,1}:
 0.9956976174312719
 0.29679718538764654
 0.22190851319074922
 0.43539176473651664
 0.12935323068115445

In [100]:
rand((2,3,5,6,7)) # va générer aléatoirement un chiffre présent dans la liste

3

In [101]:
m,n=5,3
A=rand(1:10,(m,n))

for i in 1:m
    for j in 1:n
        print(A[i,j],"\t") # '\t' permet une tabulation entre chaque chiffre
    end
    println() # permet d'aller à la ligne qd on a fini une boucle
end

8	4	3	
3	3	7	
9	6	4	
6	7	7	
6	10	4	


In [102]:
x=1
X=[x^2 for x in 1:10]
println(X)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [103]:
# itération sur un dictionnaire
dico = Dict(string(i) => cosd(i) for i=0:20:360) 
    #= i=0:20:360 -> de 0 à 360 par pas de 20.
    fonction cosd pr calculer le cosinus =#

Dict{String,Float64} with 19 entries:
  "320" => 0.766044
  "20"  => 0.939693
  "260" => -0.173648
  "220" => -0.766044
  "160" => -0.939693
  "80"  => 0.173648
  "240" => -0.5
  "360" => 1.0
  "280" => 0.173648
  "100" => -0.173648
  "40"  => 0.766044
  "140" => -0.766044
  "300" => 0.5
  "340" => 0.939693
  "0"   => 1.0
  "180" => -1.0
  "120" => -0.5
  "200" => -0.939693
  "60"  => 0.5

In [104]:
for kv in dico
    print(kv)
    # println()
end

"320" => 0.766044443118978"20" => 0.9396926207859084"260" => -0.17364817766693036"220" => -0.766044443118978"160" => -0.9396926207859084"80" => 0.17364817766693036"240" => -0.5"360" => 1.0"280" => 0.17364817766693036"100" => -0.17364817766693036"40" => 0.766044443118978"140" => -0.766044443118978"300" => 0.5"340" => 0.9396926207859084"0" => 1.0"180" => -1.0"120" => -0.5"200" => -0.9396926207859084"60" => 0.5

In [105]:
for k in keys(dico)
    println(k, " ~ ", dico[k])
end

320 ~ 0.766044443118978
20 ~ 0.9396926207859084
260 ~ -0.17364817766693036
220 ~ -0.766044443118978
160 ~ -0.9396926207859084
80 ~ 0.17364817766693036
240 ~ -0.5
360 ~ 1.0
280 ~ 0.17364817766693036
100 ~ -0.17364817766693036
40 ~ 0.766044443118978
140 ~ -0.766044443118978
300 ~ 0.5
340 ~ 0.9396926207859084
0 ~ 1.0
180 ~ -1.0
120 ~ -0.5
200 ~ -0.9396926207859084
60 ~ 0.5


In [106]:
for (key, value) in dico
    println(key, " ~ ", value)
end

320 ~ 0.766044443118978
20 ~ 0.9396926207859084
260 ~ -0.17364817766693036
220 ~ -0.766044443118978
160 ~ -0.9396926207859084
80 ~ 0.17364817766693036
240 ~ -0.5
360 ~ 1.0
280 ~ 0.17364817766693036
100 ~ -0.17364817766693036
40 ~ 0.766044443118978
140 ~ -0.766044443118978
300 ~ 0.5
340 ~ 0.9396926207859084
0 ~ 1.0
180 ~ -1.0
120 ~ -0.5
200 ~ -0.9396926207859084
60 ~ 0.5


### Importer packages

In [107]:
import Pkg
Pkg.add("DataStructures")
import DataStructures

   Updating registry at `~/.julia/registries/General`
######################################################################     96,6%####                             63,6%#################                   77,4%            84,9%##########          89,7%################# 100,0%
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`


### Condition If, Else, Elseif

In [108]:
x=readline()
y=readline()

if x<y
    println("x is less than y")
elseif x>y
    println("x is greater than y")
else           # x == y 
    println("x is equal to y")
end

stdin> 3
stdin> 8
x is less than y


In [110]:
#= 
&& AND
|| OR
=#

## Fonction

-- ***Il y a plusieurs façons d'écrire des fonctions*** --

- function nom_fct(arg)
- nom_fct(arg)
- nom_fct=arg -> ...

> 1 argument

In [111]:
function welcome(name)
    println("Welcome to Julia $name")
end

welcome("Audrey")

Welcome to Julia Audrey


In [15]:
function square(x)
    return x^2
end

square2(x)=x^2

square3=x->x^2

println("fct1: ",square(10), "; fct2: ", square2(10),  "; fct3: ", square3(10))

fct1: 100; fct2: 100; fct3: 100


In [10]:
function carre_cube(x)
    return x^2, x^3
end

carre, cube = carre_cube(2)

(4, 8)

In [46]:
carre = [power(x, 2) for x in @collect(-5, 15, 3)]
cubes = [power(x, 3) for x in @collect(-5, 15, 3)]

print("Liste de carrés: $carre & liste de cubes: $cubes")

Liste de carrés: [25, 4, 1, 16, 49, 100, 169] & liste de cubes: [-125, -8, 1, 64, 343, 1000, 2197]

> 2 arguments

In [113]:
function multiplereturn(x,y)
    return x+y, x-y, x*y, x/y, x%y
end

t=multiplereturn(2,5)
println(t)  # renvoie un tuple. 
typeof(t)

(7, -3, 10, 0.4, 2)


Tuple{Int64,Int64,Int64,Float64,Int64}

In [20]:
function power_integer(x::Int, pow::Int=2)  # x & pow doivent être des Int & par défaut pow = 2
    return x^pow
end

x = 2
carre, cube = power_integer(x), power_integer(x, 3)

println("Soit x = $x, x^2 = $(carre) & x^3 = $cube")

Soit x = 2, x^2 = 4 & x^3 = 8


In [22]:
power_integer2(x::Int, pow::Int=2) = x^pow # x & pow doivent être des Int & par défaut pow = 2

carre, cube = power_integer2(x), power_integer2(x, 3)

println("Soit x = $x, x^2 = $(carre) & x^3 = $cube")

Soit x = 2, x^2 = 4 & x^3 = 8


In [23]:
function add(x,y)::Int8 # pour transformer en entier ce qu'on rendre en argument
    return x+y
end

add(2,4.0) # -> doit retourner normalement un float si on ne specifie par '::Int8'

6

> Plusieurs arguments (...)

In [17]:
function vargs(x...) # on peut mettre n'importe quel nombre/taille
    print(x)
end

vargs(1,2,3,4,5)

(1, 2, 3, 4, 5)

In [19]:
function power(x, args...)  # x est un argument positionel
    if isempty(args)  # args tuple d'arguments
        return x^2  # par défaut détermnine le carré de x
    end
    return x^args[1]
end

x = 2
carre, cube = power(x), power(x, 3)

print("Soit x = $x, x^2 = $carre & x^3 = $cube")


Soit x = 2, x^2 = 4 & x^3 = 8

> map

- map(function,[arg]) avec arg = array

In [29]:
map(round,[1.5,3.7,2.0,8.3]) # la fonction round = arrondi 

4-element Array{Float64,1}:
 2.0
 4.0
 2.0
 8.0

In [34]:
liste=[1.5,3.7,2.0,8.3]

map(square, liste)

4-element Array{Float64,1}:
  2.25
 13.690000000000001
  4.0
 68.89000000000001

In [24]:
# la fonction est définie directement ds le map
map(x->x*10,[1,3,4,6])

4-element Array{Int64,1}:
 10
 30
 40
 60

In [122]:
# 2 fonctions
map(sqrt∘round,[3.3,2.2,9.2]) # 'round' puis 'sqrt'

3-element Array{Float64,1}:
 1.7320508075688772
 1.4142135623730951
 3.0

In [123]:
map(round∘sqrt,[3.3,2.2,9.2]) # 'sqrt' puis 'round'

3-element Array{Float64,1}:
 2.0
 1.0
 3.0

> map(function,@collect(tuple))

In [39]:
macro collect(debut, fin, args...)
    if isempty(args)
        return collect(debut:fin-1)
    end
    return collect(debut:args[1]:fin-1)
end

@collect (macro with 1 method)

In [42]:
l = @collect(-5, 15, 3) # de -5 à 14 par pas de 3.

cubes = map(x -> power(x, 3), l)

print("Soit l = $l & cubes = $cubes")

Soit l = [-5, -2, 1, 4, 7, 10, 13] & cubes = [-125, -8, 1, 64, 343, 1000, 2197]

> filter(function,@collect)

In [45]:
l = @collect(-1, 7) # de -1 à 6 par pas de 1.

even = filter(n -> iseven(n), l) # iseven renvoie les éléments pairs.

print("Les éléments paires de l sont $even")

Les éléments paires de l sont [0, 2, 4, 6]

> all

In [124]:
# all vérifie toutes les conditions
println(all(x-> x<2, (1,2,3))) # on regarde si 1<2, 2<2, 3<2 -> renvoit False car tt n'est pas <2.
println(all(x-> x<4, (1,2,3))) # on regarde si 1<4, 2<4, 3<4 -> renvoit True car tt est <4.

false
true


> any

In [125]:
# any, si une condition est rempli => OK
println(any(x-> x<2, (1,2,3))) # au moins une condition est remplit -> renvoit True.
println(any(x-> x>4, (1,2,3))) # aucune condition est rempli -> renvoit False.

true
false


### Time

In [35]:
start_time = time()
println("Execution time: $(time()-start_time)")

Execution time: 0.00023508071899414062


### Lecture fichier

In [81]:
fichier="yersinia.fasta"

if endswith(fichier, ".fasta")
    print("'$fichier' est un fichier fasta")
end

'yersinia.fasta' est un fichier fasta

In [83]:
python"""
fichier = "yersinia.fasta"
if fichier.endswith(".fasta"):
    print("'{}' est un fichier fasta".format(fichier))
"""

'yersinia.fasta' est un fichier fasta


In [ ]:
open("file1.txt", "w") do f
 # operate on file f
end  # end implicitly execute close(f)